---
- name: Install Docker
  hosts: all
  become: true
  vars_files:
    - data.yaml

  tasks:
    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"

    - name: Install packages needed for Docker
      apt:
        name: "{{ DOCKER_DEPS }}"
        state: present
        update_cache: yes

    - name: Creates keyrings dir
      file:
        path: /etc/apt/keyrings
        state: directory

    - name: Download Docker GPG apt Key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg_armored

    - name: De-Armor Docker GPG key
      command: gpg --dearmor < /usr/share/keyrings/docker-archive-keyring.gpg_armored -o /etc/apt/keyrings/docker.gpg
      no_log: 
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Save the current Ubuntu release version into a variable
      shell: lsb_release -cs
      register: ubuntu_version

    - name: Get the arch
      command: dpkg --print-architecture
      register: arch

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
        state: present
        filename: "docker"
        update_cache: no

    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"

    - name: Install Docker
      apt:
        name: "{{ DOCKER_TOOLS }}"
        state: latest
        update_cache: yes

    - name: Test Docker with hello world example
      shell: "docker run hello-world"
      register: hello_world_output

    - name: Show output of hello word example
      debug:
        msg: "Container Output: {{ hello_world_output.stdout }}"

    - name: Create docker group
      group:
        name: "docker"
        state: present

    - name: Adding user {{ lookup('env','USER') }} to docker group
      user:
        name: "{{ lookup('env','USER') }}"
        groups: "docker"
        append: "yes"